import { randomUUID } from "node:crypto";
import path from "node:path";

import * as vscode from "vscode";

import { PreviewsCodeLensProvider } from "../previews/codelens";
import {
  PREVIEW_HOST_BOOTSTRAP,
  ENV_PREVIEW_ID,
  ENV_PREVIEW_APPEARANCE,
  ENV_PREVIEW_TYPE,
  ENV_PREVIEW_REQUEST,
} from "../previews/host-bootstrap";
import { PreviewsManager } from "../previews/manager";
import { PreviewsTreeProvider } from "../previews/tree";
import type { PreviewItem } from "../previews/types";
import { targetArgs } from "./code-intelligence";
import type { RemoteClient } from "./extension";
import { config, projectRoot } from "./extension";
import type { RemoteStreams } from "./stream";

export class RemotePreviews implements vscode.Disposable {
  readonly manager = new PreviewsManager();
  private last?: PreviewItem;
  private rendering = Promise.resolve();
  private disposed = false;
  constructor(
    private readonly client: RemoteClient,
    private readonly streams: RemoteStreams,
  ) {}
  register(context: vscode.ExtensionContext): void {
    const tree = new PreviewsTreeProvider({ manager: this.manager });
    tree.start();
    this.manager.start();
    context.subscriptions.push(
      this,
      vscode.window.registerTreeDataProvider("sweetpad.previews.view", tree),
      vscode.languages.registerCodeLensProvider(
        { language: "swift", scheme: "file" },
        new PreviewsCodeLensProvider({ manager: this.manager }),
      ),
      vscode.workspace.onDidSaveTextDocument((document) => {
        if (this.last && document.languageId === "swift") {
          void this.render(this.last).catch((error) => {
            void vscode.window.showErrorMessage(`Preview refresh failed: ${String(error)}`);
          });
        }
      }),
    );
  }
  async choose(item?: PreviewItem | { preview: PreviewItem }): Promise<PreviewItem | undefined> {
    if (item) return "preview" in item ? item.preview : item;
    const items = await this.manager.getAll();
    const picked = await vscode.window.showQuickPick(
      items.map((preview) => ({ label: preview.label, description: preview.id, item: preview })),
      { placeHolder: "Select a remote SwiftUI preview" },
    );
    return picked?.item;
  }
  async setup(): Promise<void> {
    const uri = vscode.Uri.file(path.join(projectRoot(), "SweetPadPreviewHost.swift"));
    try {
      const existing = Buffer.from(await vscode.workspace.fs.readFile(uri)).toString();
      if (
        existing.startsWith("// SweetPadPreviewHost.swift — generated by SweetPad.") &&
        existing !== PREVIEW_HOST_BOOTSTRAP
      ) {
        await vscode.workspace.fs.writeFile(uri, Buffer.from(PREVIEW_HOST_BOOTSTRAP));
      }
    } catch {
      await vscode.workspace.fs.writeFile(uri, Buffer.from(PREVIEW_HOST_BOOTSTRAP));
    }
    await vscode.window.showTextDocument(uri);
    void vscode.window.showInformationMessage(
      "Call SweetPadPreviewHost.rootView() from your app's root view (see the generated file header), then build and run on the selected simulator.",
    );
  }
  async simulator(): Promise<string> {
    const selected = config()
      .get<string>("remote.destination")
      ?.match(/(?:^|,)id=([^,]+)/)?.[1];
    if (!selected) throw new Error("Select a simulator destination first.");
    const data = await this.client.query<{ destinations: { udid: string; kind: string }[] }>([
      "devices",
      "--remote",
      this.client.mac!,
    ]);
    if (!data.destinations.some((device) => device.udid === selected && device.kind === "simulator"))
      throw new Error("SwiftUI previews require a simulator destination.");
    return selected;
  }
  async render(item: PreviewItem, appearance = "light", stream = true): Promise<void> {
    const task = this.rendering.catch(() => {}).then(() => this.renderNow(item, appearance, stream));
    this.rendering = task;
    return task;
  }
  private async renderNow(item: PreviewItem, appearance: string, stream: boolean): Promise<void> {
    if (this.disposed) return;
    const simulator = await this.simulator();
    const target = targetArgs();
    const configuration = target.indexOf("--configuration");
    if (configuration >= 0) target.splice(configuration, 2);
    target.push("--configuration", "Debug");
    const request = randomUUID();
    const launched = await this.client.query<{ bundleId: string }>(
      [
        "run",
        "--detach",
        ...target,
        "--env",
        `${ENV_PREVIEW_ID}=${item.id}`,
        "--env",
        `${ENV_PREVIEW_REQUEST}=${request}`,
        ...(item.kind === "provider" ? ["--env", `${ENV_PREVIEW_TYPE}=${item.label}`] : []),
        "--env",
        `${ENV_PREVIEW_APPEARANCE}=${appearance}`,
        "--remote",
        this.client.mac!,
        "--",
        ...(config().get<string[]>("remote.xcodebuildArgs") ?? []),
        "DEAD_CODE_STRIPPING=NO",
        "SWIFT_OPTIMIZATION_LEVEL=-Onone",
      ],
      projectRoot(),
    );
    const container = await this.client.execute(
      this.client.bridgeArgs("exec", ["xcrun", "simctl", "get_app_container", simulator, launched.bundleId, "data"]),
    );
    if (container.code !== 0) throw new Error(container.stderr || "Cannot inspect preview status.");
    const statusFile = `${container.stdout.trim()}/Documents/SweetPadPreviewStatus.json`;
    const deadline = Date.now() + 15000;
    let matched = false;
    while (Date.now() < deadline) {
      const response = await this.client.execute(this.client.bridgeArgs("exec", ["cat", statusFile]));
      if (response.code === 0) {
        const status = JSON.parse(response.stdout) as { request: string; matched: boolean };
        if (status.request === request) {
          if (!status.matched)
            throw new Error(
              "The preview host could not render this preview. Check that its target includes the generated host and uses a supported SwiftUI SDK.",
            );
          matched = true;
          break;
        }
      }
      await new Promise((resolve) => setTimeout(resolve, 200));
    }
    if (!matched)
      throw new Error(
        "The app did not report preview readiness. Run SweetPad: Set Up SwiftUI Previews to update the generated host, and call its rootView() from the app root.",
      );
    if (this.disposed) return;
    this.last = item;
    if (stream) await this.streams.show(simulator);
  }
  async screenshot(item: PreviewItem, variants = false): Promise<string[]> {
    const simulator = await this.simulator();
    const paths: string[] = [];
    for (const appearance of variants ? ["light", "dark"] : ["light"]) {
      await this.render(item, appearance, false);
      await new Promise((resolve) => setTimeout(resolve, 1500));
      const file = `sweetpad-shots/preview-${Date.now()}-${appearance}.png`;
      await this.client.query(
        ["simulator", "screenshot", simulator, "--output-file", file, "--remote", this.client.mac!],
        projectRoot(),
      );
      const local = path.join(projectRoot(), file);
      paths.push(local);
      await vscode.commands.executeCommand("vscode.open", vscode.Uri.file(local), {
        viewColumn: vscode.ViewColumn.Beside,
      });
    }
    return paths;
  }
  dispose(): void {
    this.disposed = true;
    this.last = undefined;
    this.manager.dispose();
  }
}
