// Public N-API contract, available before compiling the Mac-only addon.
// Generated from the current native bindings; keep it in sync with src/lib.rs.
/* auto-generated by NAPI-RS */
/* eslint-disable */
/** One `KEY=VALUE` build setting override. */
export interface BuildSettingOverride {
  name: string
  value: string
}

/**
 * Resolve build settings for a scheme or target across a project/workspace.
 * Mirrors `xcodebuild -showBuildSettings`.
 */
export declare function buildSettings(options: BuildSettingsOptions): Array<TargetBuildSettings>

/**
 * Options for a `buildSettings` resolution — mirrors
 * `xcodebuild -showBuildSettings`. Either `project` or `workspace` is required;
 * either `scheme` or `target` selects what to resolve.
 */
export interface BuildSettingsOptions {
  project?: string
  workspace?: string
  scheme?: string
  target?: string
  configuration: string
  /**
   * SDK to bind conditionals to. Omitted, each target resolves under the
   * SDK its own `SDKROOT` names, as a plain `xcodebuild
   * -showBuildSettings` does. Ignored when `destination` is set (the
   * destination's platform wins).
   */
  sdk?: string
  /**
   * Arch to bind conditionals to. Omitted, the resolver's default, as for
   * the CLI. Ignored when `destination` is set.
   */
  arch?: string
  /** `xcodebuild -destination` string, e.g. `platform=iOS Simulator,id=…`. */
  destination?: string
  /** Extra `.xcconfig` overlay (`xcodebuild -xcconfig`). */
  xcconfig?: string
  /** A specific `Xcode.app` / `Contents/Developer` to resolve against. */
  xcode?: string
  /** `xcodebuild -derivedDataPath` override. */
  derivedDataPath?: string
  /**
   * The arguments the extension's builds add to their own
   * (`sweetpad.build.args`), read as `xcodebuild` reads them: their
   * `KEY=VALUE` settings sit above every project layer, and a `-xcconfig`,
   * `-derivedDataPath`, `-scheme` or `-configuration` among them replaces
   * the one these options name, as it does on the build's command line.
   */
  buildArgs?: Array<string>
  /**
   * The directory the build runs `xcodebuild` in, which a relative path in
   * `buildArgs` is read against.
   */
  workingDirectory?: string
  /**
   * Restrict each target's returned settings to these keys. The resolver
   * still computes the full map (settings reference each other via `$(…)`),
   * but only these keys cross the boundary — pass the handful you read to
   * avoid marshalling the full ~1.4k-entry map. Omit for every resolved key.
   */
  keys?: Array<string>
}

/**
 * Resolve the per-tool compiler/linker argument vectors (`swiftc` / `clang` /
 * link) for a scheme or target — the command lines `xcodebuild` would invoke,
 * derived from the resolved build settings. Takes the same options as
 * [`build_settings`].
 */
export declare function compilerArguments(options: BuildSettingsOptions): Array<TargetCompilerArguments>

/**
 * One generated tool invocation: the tool, its argv, and the input files it
 * compiles (`.swift` for `swiftc`, the C-family sources for `clang`; empty for
 * the linker).
 */
export interface CompilerToolInvocation {
  tool: string
  arguments: Array<string>
  inputFiles: Array<string>
}

/**
 * Build-configuration names for a `.xcodeproj` or `.xcworkspace`. For a
 * workspace, the distinct configurations across member projects.
 */
export declare function configurations(path: string): Array<string>

/**
 * An `xcodebuild -destination` argument read field by field, e.g.
 * `platform=iOS Simulator,id=<udid>,arch=x86_64`. Each field is `undefined`
 * when the argument leaves it out.
 */
export interface DestinationFields {
  /** The `platform=` (or `generic/platform=`) value as written. */
  platform?: string
  /**
   * The SDK that platform builds against (`iphonesimulator`), when the
   * platform is a known one.
   */
  sdk?: string
  /** `generic/platform=…`: a device-less build. */
  generic: boolean
  id?: string
  name?: string
  os?: string
  arch?: string
  variant?: string
}

/** A process running out of an app bundle on a device. */
export interface DevicectlAppProcess {
  pid: number
  /** The executable as devicectl reports it, a `file://` URL. */
  executable: string
  /**
   * The bundle's path on the device, decoded:
   * `/private/var/containers/Bundle/Application/<id>/My App.app`.
   */
  appPath: string
  /** Whether this is the app's own executable rather than an extension's. */
  main: boolean
}

/**
 * The processes in `devicectl device info processes --json-output` JSON that
 * run out of the `.app` directory named `appDirName` (`My App.app`). The
 * directory has to match whole, so `App.app` never matches `MyApp.app`.
 */
export declare function devicectlAppProcesses(json: string, appDirName: string): Array<DevicectlAppProcess>

/**
 * A physical device from `devicectl list devices` JSON, in either of the
 * shapes devicectl writes. Each optional field is `undefined` when devicectl
 * leaves it out.
 */
export interface DevicectlDevice {
  /** CoreDevice's identifier, which devicectl's `--device` takes. */
  identifier: string
  /**
   * The hex hardware UDID (`00008110-000559182E90401E`) xcodebuild's `id=`
   * takes. `undefined` for the entries devicectl lists with an empty
   * hardware section (some USB devices on iOS 16 and older).
   */
  udid?: string
  name?: string
  /** `iPhone 13`. */
  marketingName?: string
  /** `iPhone14,5`. */
  productType?: string
  /**
   * `iPhone`, `iPad`, `appleWatch`, `appleTV`, `appleVision`,
   * `realityDevice`.
   */
  deviceType?: string
  /** devicectl's platform, `iOS` when it reports none. */
  platform: string
  /** `27.0`. */
  osVersion?: string
  /** `connected` / `disconnected` / `unavailable`. */
  connection?: string
  /** `wired` / `localNetwork`. */
  transport?: string
  /** `paired` once the device trusts this Mac. */
  pairing?: string
  /** When the device last connected, in milliseconds since the Unix epoch. */
  lastConnectionMs?: number
}

/**
 * Every container from `root` down to `maxDepth` directories below it — the
 * walk the CLI's auto-discovery takes. Vendored trees (`Pods`,
 * `node_modules`, `Carthage`, `vendor`, `DerivedData`, `build`,
 * `SourcePackages`), dotted directories (`.build`, `.swiftpm`) and bundles
 * are never entered, nor is a symlink. Nearer directories come first, and a
 * directory's workspaces before its projects before its package, so the
 * first is the one to open when nothing says which. A promise, since a big
 * tree takes a while to read: the walk runs on a worker thread.
 */
export declare function discoverContainers(root: string, maxDepth: number): Promise<Array<DiscoveredContainer>>

/** A container the discovery walk found. */
export interface DiscoveredContainer {
  /** The `.xcworkspace`, `.xcodeproj` or `Package.swift`. */
  path: string
  /** `"workspace"`, `"project"` or `"package"`. */
  kind: string
  /** How many directories below the root it sits: 0 for one in the root. */
  depth: number
}

/**
 * Forget the session-memoized Xcode state (the `xcode-select -p` result and
 * per-install `version.plist` reads) so the next call re-detects the active
 * Xcode. The addon is long-lived inside the extension host; call this after
 * the user switches Xcode (`xcode-select -s`, a changed `DEVELOPER_DIR`) or
 * refreshes the shell environment.
 */
export declare function flushXcodeCache(): void

/**
 * The build settings a hot-reload build for `sdk` adds, in order: an
 * interposable link and frontend command lines, and on macOS no hardened
 * runtime or App Sandbox, without which injection fails silently. Empty when
 * hot reload can't inject into `sdk` (devices, watchOS).
 */
export declare function hotReloadBuildSettings(sdk: string): Array<BuildSettingOverride>

/**
 * The InjectionNext client dylib that injects into apps built for `sdk`, or
 * null when hot reload can't inject into it.
 */
export declare function hotReloadDylibName(sdk: string): string | null

/**
 * The `<Platform>.platform` directory of an injectable `sdk`, where the
 * InjectionNext.app client finds the XCTest it links; null otherwise.
 */
export declare function hotReloadPlatformDir(sdk: string): string | null

/** List a `.xcodeproj`'s targets, configurations, and schemes. */
export declare function listProject(path: string): ProjectInfo

/**
 * List a `.xcworkspace`'s member projects, member packages, and merged
 * schemes.
 */
export declare function listWorkspace(path: string): WorkspaceInfo

/**
 * Find the app a build with these options writes, through the in-process
 * resolver: the target the scheme's Run action launches, or the one that
 * runs on the destination, with the product path, bundle id and executable
 * the build's own arguments give it. The CLI's `app` verbs locate the app
 * the same way. `keys` trims the located target's returned settings.
 */
export declare function locateApp(options: BuildSettingsOptions): LocatedApp

/**
 * The app a build produced: the target that builds it, the `.app` path, its
 * bundle id, the executable inside it, and the target's resolved settings.
 */
export interface LocatedApp {
  target: string
  path: string
  bundleId: string
  /** `TARGET_BUILD_DIR/EXECUTABLE_PATH`, the binary to run for a macOS app. */
  executable: string
  settings: Record<string, string>
}

/**
 * The `.xcscheme` file behind the scheme `name` of a `.xcworkspace`,
 * `.xcodeproj` or `Package.swift`: the one `xcodebuild` reads, from the
 * container, its member projects and its local packages, and only the
 * current user's `xcuserdata`. `null` for a scheme with no file (autocreated)
 * or a name the container doesn't list.
 */
export declare function locateScheme(container: string, name: string): string | null

/**
 * Which toolchain evaluates the manifests a names read needs. The extension
 * host sees neither the login shell's `DEVELOPER_DIR` nor
 * `sweetpad.build.swiftCommand`, so the extension passes both.
 */
export interface ManifestToolchain {
  /** The `swift` to run, when not the one on `PATH`. */
  swift?: string
  /** The `DEVELOPER_DIR` to run it under. */
  developerDir?: string
}

/**
 * Read a `-destination` argument the way the CLI does. Never fails: an
 * unknown platform just has no `sdk`.
 */
export declare function parseDestination(destination: string): DestinationFields

/**
 * Parse `devicectl list devices --json-output` JSON into the physical
 * devices, sorted by name. The simulators Xcode 27's devicectl lists beside
 * them are left out: `parseSimulators` reads those from simctl.
 */
export declare function parseDevicectlDevices(json: string): Array<DevicectlDevice>

/**
 * Parse a single `.xcscheme` file into its actions + per-action
 * configurations. Pair with `buildSettings` to resolve only the runnable
 * target instead of every buildable in the scheme.
 */
export declare function parseScheme(path: string): SchemeInfo

/**
 * Parse `simctl list --json devices` output into the available simulators,
 * in the CLI's picker order. Unavailable simulators are left out.
 */
export declare function parseSimulators(json: string): Array<SimctlSimulator>

/**
 * Pick the app among build settings resolved outside the addon (through a
 * customized `xcodebuild`), by the rules [`locate_app`] uses.
 */
export declare function pickApp(options: PickAppOptions): LocatedApp

/** Options for [`pick_app`]. */
export interface PickAppOptions {
  /**
   * Each target's settings, as `xcodebuild -showBuildSettings` reported
   * them for the build.
   */
  targets: Array<TargetBuildSettings>
  /**
   * The `.xcodeproj` or `.xcworkspace` and the scheme the settings are
   * for: the scheme's Run action names the target Xcode launches.
   */
  container: string
  scheme: string
  /** The build's `xcodebuild -destination` string. */
  destination?: string
  /** The build's SDK, which narrows the pick when there is no destination. */
  sdk?: string
  /** Restrict the picked target's returned settings to these keys. */
  keys?: Array<string>
}

/**
 * A single `.xcodeproj`'s targets, configurations, and schemes (shared +
 * per-user, or autocreated per-target when no scheme file exists).
 * Mirrors `xcodebuild -list -project`.
 */
export interface ProjectInfo {
  name: string
  targets: Array<string>
  configurations: Array<string>
  schemes: Array<string>
}

/**
 * A target referenced by a scheme (a build entry or a testable). Mirrors a
 * `BuildableReference` in the `.xcscheme` XML.
 */
export interface SchemeBuildable {
  /** Target name — matches a `listProject` / `listWorkspace` target. */
  blueprintName: string
  /** The target's pbxproj UUID. */
  blueprintIdentifier: string
  /** Produced artifact filename, e.g. `Foo.app`. */
  buildableName: string
  /** `ReferencedContainer`, e.g. `container:Foo.xcodeproj`. */
  container: string
}

/**
 * One row of a scheme's Build action, with the five `buildFor*` flags. The
 * app a scheme launches is the first entry whose `forRunning` is true.
 */
export interface SchemeBuildEntry {
  buildable: SchemeBuildable
  forRunning: boolean
  forTesting: boolean
  forProfiling: boolean
  forArchiving: boolean
  forAnalyzing: boolean
}

/** A command-line argument under a scheme's `LaunchAction`. */
export interface SchemeCommandLineArgument {
  argument: string
  isEnabled: boolean
}

/** An environment variable under a scheme's `LaunchAction`. */
export interface SchemeEnvironmentVariable {
  key: string
  value?: string
  isEnabled: boolean
}

/**
 * Every file named for the scheme `name` in the places [`locate_scheme`]
 * looks, the one it returns first.
 */
export declare function schemeFiles(container: string, name: string): Array<string>

/**
 * A parsed `.xcscheme`: its Build entries (with the `buildFor*` flags), Test
 * action, and each action's default build configuration — the scheme-level
 * facts `xcodebuild -showBuildSettings` can't tell you (which target a scheme
 * launches, the config it defaults to, …).
 */
export interface SchemeInfo {
  buildEntries: Array<SchemeBuildEntry>
  buildImplicitDependencies: boolean
  parallelizeBuildables: boolean
  testAction?: SchemeTestAction
  /**
   * The single target the scheme launches (`LaunchAction`'s runnable) — use
   * this to pick which target's `buildSettings` to resolve, rather than
   * guessing from `buildEntries[].forRunning`.
   */
  launchTarget?: SchemeBuildable
  launchConfiguration?: string
  profileConfiguration?: string
  archiveConfiguration?: string
  analyzeConfiguration?: string
  launchArguments: Array<SchemeCommandLineArgument>
  launchEnvironmentVariables: Array<SchemeEnvironmentVariable>
  launchLanguage?: string
  launchRegion?: string
  /**
   * Whether an enabled launch argument or environment value refers to a
   * build setting, so `schemeLaunchSettings` needs resolved settings to
   * expand it.
   */
  launchReferencesSettings: boolean
}

/**
 * The arguments and environment Xcode launches the app of the scheme at
 * `path` with: enabled rows only, `$(VAR)` expanded, arguments split with
 * shell-style quoting, then the App Language and App Region flags.
 * `buildSettings` are the scheme's resolved targets. Those of its expansion
 * target (the Run action's `MacroExpansion`, else the target it launches,
 * else the first) expand `$(VAR)`. An empty list is enough when
 * `parseScheme(path).launchReferencesSettings` is false.
 */
export declare function schemeLaunchSettings(path: string, buildSettings: Array<TargetBuildSettings>): SchemeLaunchSettings

/** What a scheme's Run action launches its app with. */
export interface SchemeLaunchSettings {
  /** Process arguments, in launch order. */
  args: Array<string>
  env: Record<string, string>
}

/**
 * Scheme names for a `.xcodeproj`, `.xcworkspace` or `Package.swift` —
 * shared and per-user scheme files, plus autocreated per-target schemes, plus
 * the products of every local SwiftPM package the container reaches. For a
 * workspace, merged across the bundle and every member project, sorted like
 * `xcodebuild -list -workspace`. For a package, its `.swiftpm/xcode` scheme
 * files and the schemes its manifest synthesizes, sorted like `xcodebuild
 * -list` in its directory. `toolchain` evaluates the manifests.
 */
export declare function schemes(path: string, toolchain?: ManifestToolchain | undefined | null): Promise<Array<string>>

/** A testable in a scheme's Test action. */
export interface SchemeTestable {
  buildable: SchemeBuildable
  skipped: boolean
}

/** A scheme's Test action. */
export interface SchemeTestAction {
  configuration: string
  testables: Array<SchemeTestable>
  codeCoverageEnabled: boolean
}

/** A simulator from `simctl list --json devices`. */
export interface SimctlSimulator {
  udid: string
  name: string
  /** `Booted` / `Shutdown` / `Booting` …, as simctl reports it. */
  state: string
  /** The runtime's OS: `iOS`, `watchOS`, `tvOS`, `xrOS`. */
  os: string
  /** `27.0`. */
  osVersion: string
  /** `com.apple.CoreSimulator.SimRuntime.iOS-27-0`. */
  runtime: string
  /**
   * `com.apple.CoreSimulator.SimDeviceType.iPhone-17`; empty when simctl
   * leaves it out.
   */
  deviceTypeIdentifier: string
  /** The `-destination` specifier for it: `platform=iOS Simulator,id=<udid>`. */
  destination: string
}

/**
 * The platforms (`SUPPORTED_PLATFORMS` tokens, `iphonesimulator`) the
 * scheme's targets build for under `configuration`, read from the targets'
 * authored settings the way the CLI's destination picker reads them. `null`
 * when that can't be told (a Swift package, an unreadable project, targets
 * that author neither `SUPPORTED_PLATFORMS` nor `SDKROOT`): offer every
 * destination then.
 */
export declare function supportedPlatforms(container: string, scheme: string, configuration: string): Array<string> | null

/** One target's resolved build settings (`{ KEY: VALUE }`). */
export interface TargetBuildSettings {
  target: string
  settings: Record<string, string>
}

/**
 * One target's generated per-tool compiler/linker argv. A field is absent when
 * the target has no inputs for that tool.
 */
export interface TargetCompilerArguments {
  target: string
  swift?: CompilerToolInvocation
  clang?: CompilerToolInvocation
  link?: CompilerToolInvocation
}

/**
 * Target names for a `.xcodeproj`, `.xcworkspace` or `Package.swift`. For a
 * workspace, the distinct targets across member projects in first-seen
 * order; then, for either, each local package's targets — test targets
 * included, since a target list drives `-only-testing:`. For a package, every
 * target its manifest declares.
 */
export declare function targets(path: string, toolchain?: ManifestToolchain | undefined | null): Promise<Array<string>>

/**
 * A `.xcworkspace`'s declared `.xcodeproj` paths and merged schemes (the
 * workspace bundle's own plus every member project's, shared + per-user,
 * or autocreated per-target when no scheme file exists anywhere).
 * Mirrors `xcodebuild -list -workspace`, plus the `projects` paths.
 */
export interface WorkspaceInfo {
  name: string
  /** Absolute paths of every `.xcodeproj` the workspace declares, in order. */
  projects: Array<string>
  /**
   * Absolute paths of every local SwiftPM package the workspace declares.
   * Their products are NOT in `schemes`: naming those needs a manifest
   * evaluation, which only the async [`schemes`] does.
   */
  packages: Array<string>
  schemes: Array<string>
}

/**
 * Resolve the Xcode toolchain info. `developer_dir` pins a specific install
 * (the extension passes its login shell's `DEVELOPER_DIR`, which this
 * process's own environment doesn't see); omitted, the active Xcode (env
 * `DEVELOPER_DIR`, else `xcode-select -p`) is detected.
 */
export declare function xcodeVersion(developerDir?: string | undefined | null): XcodeVersion

/**
 * Active Xcode toolchain info. Mirrors `xcrun xcodebuild -version` plus the
 * resolved `DEVELOPER_DIR`.
 */
export interface XcodeVersion {
  developerDir: string
  shortVersion: string
  buildVersion: string
  majorVersion: number
}
